version: 0.2 

batch:
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
    dynamic:
      env:
        image:
          - aws/codebuild/amazonlinux2-x86_64-standard:3.0
        variables:
          MY_VAR:
            - "codebuild.java.AppTest"
            - "codebuild.java.IoTest"
            - "codebuild.java.UserTest"
phases: 
  install: 
    commands:
      - gradle -v 
  build: 
    commands: 
      - echo "yeah------"
      - echo $MY_VAR
      - gradle clean
      - gradle assemble
      - gradle test -i --tests $MY_VAR

artifacts:
  files:
    - build/reports/**/*
  discard-paths: no
  