/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codebuild.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class IoTest {
    @Test public void testIoSuccess() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testIoFail() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
