/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codebuild.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class UserTest {
    @Test public void testUserSuccess() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testUserFail() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testNothingToDo() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
